### PR TITLE
Intertype + ACSets

### PR DESCRIPTION
**Pull request by olynch**

### CODE REVIEW

**Comment by olynch** [comment]
I think the coverage on this isn't being correctly computed, because there are lines in the tests which exercise read/write of acsets, but the coverage says that the read/write methods aren't being called... Anyways, LGTM

**Comment by olynch** [comment]
TODO:

- support for kwargs to `@acset_type`
- schema inheritance
- declare multiple things in one line, i.e. `(a,b)::Ob`

**Review by jpfairbanks — APPROVED** [review]

**Comment by jpfairbanks** [comment]
@olynch do you think this is ready for merge today?

**Comment by olynch** [comment]
The remaining issue with this is that I would like to test py-acsets integration in the CI.

**Pull request merged**
